import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillFilePdf,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import oraFinanceMockup from "../public/ora_finance_mockup.png";
import oraFinanceMockup2 from "../public/ora_finance_mockup_2.png";
import oraFinanceMockup3 from "../public/ora_finance_mockup3.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const handleRedirect = () => {
    window.open ('https://github.com/atharavmishra','_blank');
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by Atharv</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
               

                 <a
      className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
      href="#"
      onClick={handleRedirect}
    >
      Github
    </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Atharv Mishra
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Android App developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Hi, I am Atharv Mishra a passionate Android developer with over 2.5 years of Experience. I love building Apps that create magic 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillFilePdf />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            
          <div className="text-start shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex" style={{ height: '600px' }}>
  <div style={{ width: '300px', height: '100%', position: 'relative' }}>
    <Image src={oraFinanceMockup2} layout="fill" objectFit="cover" />
  </div>
  <div style={{ width: '300px', height: '100%', position: 'relative' }}>
    <Image src={oraFinanceMockup} layout="fill" objectFit="cover" />
  </div>
  <div style={{ width: '300px', height: '100%', position: 'relative' }}>
    <Image src={oraFinanceMockup3} layout="fill" objectFit="cover" />
  </div>
  <div className="flex-1 ml-4">
    <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
      Ora Finance
    </h3>
    <p className="py-2">
      Creating elegant designs suited for your needs following core
      design theory.
    </p>
    <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
    <p className="text-gray-800 py-1">Photoshop</p>
    <p className="text-gray-800 py-1">Illustrator</p>
    <p className="text-gray-800 py-1">Figma</p>
    <p className="text-gray-800 py-1">Indesign</p>
  </div>
</div>


            
           
             </div>

             <div className="lg:flex gap-10">
            
            <div className="text-start shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex" style={{ height: '600px' }}>
    <div style={{ width: '300px', height: '100%', position: 'relative' }}>
      <Image src={oraFinanceMockup2} layout="fill" objectFit="cover" />
    </div>
    <div style={{ width: '300px', height: '100%', position: 'relative' }}>
      <Image src={oraFinanceMockup} layout="fill" objectFit="cover" />
    </div>
    <div style={{ width: '300px', height: '100%', position: 'relative' }}>
      <Image src={oraFinanceMockup3} layout="fill" objectFit="cover" />
    </div>
    <div className="flex-1 ml-4">
      <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
        Ora Finance
      </h3>
      <p className="py-2">
        Creating elegant designs suited for your needs following core
        design theory.
      </p>
      <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
      <p className="text-gray-800 py-1">Photoshop</p>
      <p className="text-gray-800 py-1">Illustrator</p>
      <p className="text-gray-800 py-1">Figma</p>
      <p className="text-gray-800 py-1">Indesign</p>
    </div>
  </div>
  
  
              
             
               </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
